### ISSUE TITLE
Final expression in codegenChain not being run

### ISSUE THREAD

**Issue by purefunctor** [purescm/purescm#116]
This has to do with how codegenChain is currently defined. Reading through initially, this might have to do with how EffectPure is being unwrapped as a special case rather than being handled in the "final" step in the accumulation.

**Comment by JordanMartinez** [comment]
Can you provide a reproducible example that isn't dependent on #109? Meaning, is this triggered specifically by your conversion for the uncurried effect fns? Or does it work on curried effects, too?

**Comment by purefunctor** [comment]
This should just fail to print `world` outright:
```
module Main where

import Prelude

import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = do
  log "hello"
  log "world"
```
