### ISSUE TITLE
Port core libraries

### ISSUE THREAD

**Issue by anttih** [purescm/purescm#170]
A tracking issue for porting all the core libraries to `purescm`. Core packages are in a [single monorepo](https://github.com/purescm/purescript-core).

Packages that don't have any foreign definitions can just be added to the package-set from the upstream registry.

- [x] prelude
- [x] unsafe-coerce
- [x] safe-coerce
- [x] newtype
- [x] control
- [x] invariant
- [x] const
- [x] maybe
- [x] either
- [x] tuples
- [x] bifunctors
- [x] contravariant
- [x] identity
- [x] type-equality
- [x] distributive
- [x] exists
- [x] profunctor
- [x] functors
- [x] orders
- [x] foldable-traversable
- [x] functions
- [x] partial
- [x] unfoldable
- [x] nonempty
- [x] effect
- [x] refs
- [x] tailrec?
- [x] st
- [x] arrays
- [x] gen
- [x] enums
- [x] numbers
- [x] integers
- [x] lazy
- [x] lists
- [x] ordered-collections
- [x] exceptions
- [x] transformers
- [x] parallel
- [x] record
- [x] catenable-lists
- [x] free
- [x] random
- [x] console
- [x] assert
- [x] filterable
- [x] semirings
- [x] validation
- [x] minibench
- [x] strings
- [x] quickcheck
- [x] lcg
- [x] datetime
- [x] foreign-object
- [ ] ~~foreign~~ Probably not relevant
- [x] json

**Comment by anttih** [comment]
I will work on `foldable-traversable` next.

**Comment by f-f** [comment]
These are "pure" and can be just added from the registry once their dependencies are ported:
- nonempty
- transformers
- catenable-lists
- free
- filterable
- validation

**Comment by postsolar** [comment]
`lists` is pure too.

**Comment by anttih** [comment]
I will work on `st` next.

**Comment by anttih** [comment]
I will work on `arrays` next.

**Comment by postsolar** [comment]
I will work on `strings` next. I think I'm done with `foreign` but I'll need `strings` and `arrays` to test it.

**Comment by postsolar** [comment]
`records` is marked as done and is present in the packageset but if I'm not mistaken one of the modules of the package uses API which isn't SRFI 125 and the other module is not yet implemented.

**Comment by f-f** [comment]
This is finally done as of https://github.com/purescm/purescript-core/issues/13 🎉
