### ISSUE TITLE
Don't emit constructor checks when dealing with types with a single constructor

### ISSUE THREAD

**Issue by turlando** [purescm/purescm#27]
When we have
`data Foo = Foo`
we translate it into
`(cons 'Foo . (vector))`

When we have
`f Foo = 23`
we always check if `(car v)` is `'Foo` but it always will be because the type checker will not allow otherwise.

Cfr. https://github.com/turlando/purescm/pull/26#discussion_r639454003

**Comment by turlando** [comment]
Discussion continues from [here](https://github.com/turlando/purescm/issues/30#issuecomment-850787472)

**Comment by f-f** [comment]
We need to verify how the new implementation handles this, and if we need to do anything at all

**Comment by turlando** [comment]
Since #97, the following code

```purescript
data NoArgs = NoArgs

test1 :: NoArgs -> Boolean
test1 = case _ of
  NoArgs -> true

foo :: Boolean
foo = test1 NoArgs
```

compiles into

```scheme
(scm:define NoArgs
  (scm:quote NoArgs))

(scm:define NoArgs?
  (scm:lambda (v)
    (scm:eq? (scm:quote NoArgs) v)))

(scm:define test1
  (scm:lambda (v0)
    #t))

(scm:define foo
  #t)
```

So I think we can close this issue?
