### ISSUE TITLE
Don't always use `letrec*`

### ISSUE THREAD

**Issue by turlando** [purescm/purescm#60]
Right now for implementation simplicity we're always emitting `letrec*` where `let` or `let*` would be sufficient. This might have a performance impact.

**Comment by f-f** [comment]
This still applies to the PS implementation, so I'll leave it open

**Comment by JordanMartinez** [comment]
In what way? The PS implementaiton distinguishes between recursive binding groups and non-recursive binding-groups. So, I would assume we would use `letrec*` for the first and `let`/`let*` for the second depending on the number of bindings in that group.

**Comment by anttih** [comment]
We don't emit `letrec` for non-recursive bindings.
