### ISSUE TITLE
Move to spago-next

### ISSUE THREAD

**Issue by f-f** [purescm/purescm#70]
It should make it easier to juggle the custom package set.

I was getting started on this, but realised that I need to fix [spago itself](https://github.com/purescript/spago/blob/ad81065f577436185bd0fe4bfb88714363ffca15/spaghetto/src/Spago/Config.purs#L154) before this setup can work.

**Comment by JordanMartinez** [comment]
Oh, because the new spago better supports multiple backends for when we need to write FFI, right?

**Comment by f-f** [comment]
The main reason is better handling of package sets - we don't need to specify dependencies when assemnling a package set for the backend, but can just pull them from the packages themselves.

**Comment by f-f** [comment]
Fixed in #94
