### ISSUE TITLE
Pretty-print generated Chez Scheme output

### ISSUE THREAD

**Issue by purefunctor** [purescm/purescm#74]
Right now, not much pretty-printing is being done for generated Scheme sources. A possible approach to take is to create a separate syntax for the pretty-printer such that we wouldn't have to wrangle with `Dodo` primitives or pattern matching against the core syntax.

**Comment by JordanMartinez** [comment]
I'll submit a PR later tonight or tomorrow morning that adds some pretty printing by redefining the Chez Scheme syntax to better adhere to the spec.

**Comment by JordanMartinez** [comment]
Should we model [`expr`](https://github.com/JordanMartinez/purs-backend-cs/blob/master/chez-scheme-eBNF.md?plain=1#L119-L127)? If so, how much of it should we model (I'm also thinking how well/poorly this will help when it comes to parsing FFI)?
Or should we continue to use the current `ChezExpr` type?

#76 is the PR I mentioned above.

**Comment by JordanMartinez** [comment]
Small nitpick, but do ya'll mind if we change the alias for `Dodo` to just `D`? I have a habit of writing `D.text`, but here I need to write `Dodo.text`. If so, I can do that in a separate PR.

**Comment by purefunctor** [comment]
> Should we model [`expr`](https://github.com/JordanMartinez/purs-backend-cs/blob/master/chez-scheme-eBNF.md?plain=1#L119-L127)? If so, how much of it should we model (I'm also thinking how well/poorly this will help when it comes to parsing FFI)? Or should we continue to use the current `ChezExpr` type?
> 
> #76 is the PR I mentioned above.

So far I haven't run anything that the `ChezExpr` type isn't able to model (aside from quoted stuff, I guess), but I think it's reasonable to model `expr` for completion.

> Small nitpick, but do ya'll mind if we change the alias for `Dodo` to just `D`?

Do go for it!

**Comment by JordanMartinez** [comment]
Closed by #76 and #79.

> What's the rationale for modeling the whole expr? If this is output-only (i.e. only printing out code) then we don't really need much syntax at all

I think we can further discuss this in a separate issue, but I think you're right: for output-only, we don't need the `expr` syntax.
