### ISSUE TITLE
32-bit `Int` and Fixnum

### ISSUE THREAD

**Issue by purefunctor** [purescm/purescm#82]
R6RS [defines](http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_sec_11.2) the fixnum range to be a closed interval of:
```
[-2^w, 2^(w-1) - 1]
```
Where `w` is an integer that's `> 24`. For Chez, `w` or the `(fixnum-width)` is `61` on 64-bit platforms, meaning that we'll have to do some truncation logic if we want to keep the invariant that `Int` is 32-bit. I'm not sure what's being done in purerl but is it the case that `Int` is just not a 32-bit type there at all?

**Comment by turlando** [comment]
The BEAM uses 28 bits and 60 bits on 32 and 64 bits architectures respectively for "small integers". It looks like it transforms numbers transparently to "large integers". Cf. https://www.erlang.org/doc/efficiency_guide/advanced.html

**Comment by JordanMartinez** [comment]
I think we should drop the 32-bit invariant. My assumptions are:
- adding such truncation logic will unnecessarily slow down integer-heavy code
- that some want the capability of a larger Int

**Comment by anttih** [comment]
It the prelude now we have dropped the 32 invariant. `Int` is a fixnum. One drawback is that when it overflows `chez` throws an exception, which can happen with any operation.
