### ISSUE TITLE
Escape identifiers

### ISSUE THREAD

**Issue by purefunctor** [purescm/purescm#91]
Make sure to escape characters that are valid in PureScript grammar e.g. `'` and are not in Chez Scheme.

**Comment by natefaubion** [comment]
Note that "identifiers" in CoreFn are not grammatically PureScript identifiers. They are arbitrary strings.

**Comment by turlando** [comment]
From [TSPL Section 1.1](https://scheme.com/tspl4/intro.html#./intro:h1):

> Scheme programs are made up of keywords, variables, structured forms, constant data (numbers, characters, strings, quoted vectors, quoted lists, quoted symbols, etc.), whitespace, and comments.
>
> Keywords, variables, and symbols are collectively called identifiers. Identifiers may be formed from letters, digits, and certain special characters, including ?, !, ., +, -, *, /, <, =, >, :, $, %, ^, &, _, ~, and @, as well as a set of additional Unicode characters. Identifiers cannot start with an at sign ( @ ) and normally cannot start with any character that can start a number, i.e., a digit, plus sign ( + ), minus sign ( - ), or decimal point ( . ). Exceptions are +, -, and ..., which are valid identifiers, and any identifier starting with ->. For example, hi, Hello, n, x, x3, x+2, and ?$&*!!! are all identifiers. Identifiers are delimited by whitespace, comments, parentheses, brackets, string (double) quotes ( " ), and hash marks( # ). A delimiter or any other Unicode character may be included anywhere within the name of an identifier as an escape of the form \xsv;, where sv is the scalar value of the character in hexadecimal notation.

From [CSUG, Section 1.1](https://cisco.github.io/ChezScheme/csug9.5/intro.html#./intro:h1)

> Chez Scheme extends the syntax of identifiers in several ways. First, the sequence of characters making up an identifier's name may start with digits, periods, plus signs, and minus signs as long as the sequence cannot be parsed as a number. For example, 0abc, +++, and .. are all valid identifiers in Chez Scheme. Second, the single-character sequences { and } are identifiers. Third, identifiers containing arbitrary characters may be printed by escaping them with \ or with |. \ is used to escape a single character (except 'x', since \x marks the start of a hex scalar value), whereas | is used to escape the group of characters that follow it up through the matching |. For example, \||\| is an identifier with a two-character name consisting of the character | followed by the character \, and |hit me!| is an identifier whose name contains a space.

Even if ' is not explicitly mentioned in the above paragraphs I know it's legal to use it as a trailing character in scheme symbols.

```
> (define foo' 23)
> foo'
23
```

That being said maybe it's a good idea to avoid it?

**Comment by JordanMartinez** [comment]
> That being said maybe it's a good idea to avoid it?

Why is it a good idea?

**Comment by natefaubion** [comment]
One thing to consider in general is if this backend should try to generate portable scheme or if it's only goal is to target chez specifically.

**Comment by JordanMartinez** [comment]
It was my understanding that this backend is only targeting chez scheme.

**Comment by purefunctor** [comment]
> That being said maybe it's a good idea to avoid it?

Yeah, I think the problem with it comes from when the identifier appears in the export list near a parenthesis.

**Comment by JordanMartinez** [comment]
Ah...

> when the identifier appears in the export list near a parenthesis.
I'm not against avoiding it, but if this did happen, wouldn't there be a bug in our codegen printer?

**Comment by turlando** [comment]
> [...] wouldn't there be a bug in our codegen printer?

I guess we've been lucky so far

```
#!r6rs
#!chezscheme
(library
  (foo)
  (export
    foo')
  (import
    (prefix (chezscheme) scm:)
    (prefix (_Chez_Runtime lib) rt:))

  (scm:define foo' "foo"))
```

```
% scheme --libdirs /home/u/purescm/test-snapshots/test-out: --script foo.ss
Exception in read: unexpected close parenthesis at line 6, char 9 of foo.ss
```

**Comment by purefunctor** [comment]
> They are arbitrary strings.

If this is the case, is defining a `escapeIdentifier` function that gets changed every now and then for special cases a good enough solution?

**Comment by JordanMartinez** [comment]
Note that even a prime in-between characters fails: `foo'oo`.
