### ISSUE TITLE
More structured data type for Scheme expressions

### ISSUE THREAD

**Issue by turlando** [purescm/purescm#95]
Right now we're emitting raw forms (lists and atoms). In order to have better pretty-printing and, most of all, cleaner code it might be a good idea to produce a richer data type representing Scheme code.

@JordanMartinez and @purefunctor pointed out that we should keep a way to emit "raw" scheme forms using the data type we already have (ChezExpr), something like

```
data ChezExpr
  = ManualExpr ChezManualExpr
  | KnownExpr ChezKnownExpr
```

I'm opening this issue to discuss the actual shape of such data structure and the constructors we will need.

**Comment by turlando** [comment]
My first question is: do we want to express as much as possible in this data type?

Let me explain using an example. I think it makes sense to have `cond` in the new data type, given it's importance and the way it should be printed¹. I'm not entirely sure we want to create a constructor for, say, `eq?`: while it's very common as well, maybe we can define it as an helper function like `eqQ x y = App "eq?" [ x, y ]`.

I'm not entirely sure what's the best design in the long term.

¹:
```
(cond
  [c1 e1]
  [c2 e2]
  [else e3])
```

**Comment by f-f** [comment]
I'd say ultimately this should be driven by the pretty-printing: you'll want `Cond` and `Let` and `Define` and so on because they need special formatting, but there will not be much difference between let's say `not` and `eq?`, so they can both use `App`.

**Comment by JordanMartinez** [comment]
I tried out the two constructor approach and found it not ergonomic. What happens when a KnownExpr contains a ManualExpr that contains a KnownExpr? I think it may be easier to just merge the two into one type.

**Comment by JordanMartinez** [comment]
Something like that. I think we should wait for #109 to get merged before doing this refactor.

**Comment by turlando** [comment]
Do we want ChezExpr to include atoms (symbols, integers, strings) and lists as well? Because if that's the case the issue is already solved. But that would be an uncontrolled way to create forms, which I'm not sure it's something we really want.

Another solution would be to only have KnownExprs and use the FFI to expose more complex forms and functions.

**Comment by JordanMartinez** [comment]
Just a few thoughts I had while working on #119:
- I think pretty-printing `lets` should use brackets rather than parenthesis to indicate the start/end of the bound values. For example
```scheme
(scm:let
  [(foo "foo")
  (bar "bar")
  (baz "baz")]
  (boydExpression))
```

- Should we update `codegenEnv` to include whether to print lists using parens or brackets next? Per R6RS, swapping between these two boundaries helps clarify start/end points of said boundaries:
```
(define foo
  (lambda [bar]
    (lambda [baz]
      (let [(foo1 1) (foo2 2)]
        foo3))))
```

**Comment by turlando** [comment]
> * I think pretty-printing `lets` should use brackets rather than parenthesis to indicate the start/end of the bound values. For example
> 
> 
> ```scheme
> (scm:let
>   [(foo "foo")
>   (bar "bar")
>   (baz "baz")]
>   (boydExpression))
> ```

From the reader point of view, it is exactly the same code. From a convention point of view, it is common to use [] to delimit the single binding and () to delimit the binding group. Also `(boydExpression)` should not be aligned to `(baz "baz")`.
